### ISSUE TITLE
Invisible users on list

### ISSUE THREAD

**Issue by Demorde** [amonchakai/Hg10#13] opened 2015-02-10 22:31 UTC
Hello,

I am using Hg10 on my Passport with my own (non Google) XMPP account. It logs in and in the log it shows my contact accounts (though with a 0 instead of a 1) and then they do not display on the contact list. However when the contacts message me the phone gets notified but there is no way to interact with them.

**Comment by amonchakai** [comment] 2015-02-12 15:28
Hi,

Sorry for the late reply, I was busy lately.
I will check this, I have an idea of what is hapenning.
What you see in the log with the 0 and 1 are presence information. 0 means available, so I am pretty sure this part is fine.
The issue is rather receiving the list of contacts. I think I am discarding the contact because I don't have a name nor a nickname. Well, I know I do that, and I guess it is what is happening to you. 
I will improve this.

**Comment by Demorde** [comment] 2015-04-10 17:52
This still hasn't been fixed, on two separate accounts from two separate servers any contacts that are not from Google do not show up on the list, however they can message me and the phone notifies me that there is activity but there is no way to interact with them.

**Comment by amonchakai** [comment] 2015-04-10 18:17
I thought I fixed it, but OK, I will check it again.

**Comment by Demorde** [comment] 2015-04-10 19:36
I am willing to give you an account on my xmpp server which is giving issues if it'll help, and the other is the fsf.org xmpp server which you get if you are a donating member.

**Comment by amonchakai** [comment] 2015-04-12 15:34
Hi,

I usually use jabber.de for my tests...
I pushed a fix on the store with few other stuff. Don't hesitate to put another bump if it does not work.

**Comment by Demorde** [comment] 2015-04-13 19:58
I'll give an update when it updates on the store, the current version is still the Mar 25 release.

**Comment by Gh10User** [comment] 2015-04-18 06:22
I m adding a contact of one of my friend but then also it dosent response anything, it just not working for what I need it

**Comment by Gh10User** [comment] 2015-04-18 06:22
I m adding a contact of one of my friend but then also it dosent response anything, it just not working for what I need it

**Comment by amonchakai** [comment] 2015-04-18 08:54
Ok, I will check that as well.

**Comment by amonchakai** [comment] 2015-06-03 20:01
will be solved in the next release.

**Closed by amonchakai** 2015-06-03 20:01 UTC
Labels: bug
